/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractStatemachineScopeProvider extends XtypeScopeProvider {
}
