/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class StatemachineProposalProvider extends AbstractStatemachineProposalProvider {
}
