/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing.parser.antlr;

import com.google.inject.Inject;
import de.darmstadt.tu.crossing.parser.antlr.internal.InternalStatemachineParser;
import de.darmstadt.tu.crossing.services.StatemachineGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class StatemachineParser extends AbstractAntlrParser {

	@Inject
	private StatemachineGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStatemachineParser createParser(XtextTokenStream stream) {
		return new InternalStatemachineParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Statemachine";
	}

	public StatemachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StatemachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
