/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatemachineAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/darmstadt/tu/crossing/parser/antlr/internal/InternalStatemachine.tokens");
	}
}
