/**
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing;

import de.darmstadt.tu.crossing.StatemachineStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {
  public static void doSetup() {
    new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
