/**
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing;

import de.darmstadt.tu.crossing.AbstractStatemachineRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatemachineRuntimeModule extends AbstractStatemachineRuntimeModule {
}
