/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {

	def static void doSetup() {
		new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
