/*
 * generated by Xtext 2.23.0
 */
package de.darmstadt.tu.crossing


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StatemachineRuntimeModule extends AbstractStatemachineRuntimeModule {
}
